name = "webhook-listener"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "webhook-listener-db"
database_id = ""

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "webhook-listener-db"
database_id = ""